"""
Trinity Voice API
=================
FastAPI backend that exposes Trinity's brain over HTTPS for the mobile app.

Endpoints
---------
  POST /api/auth/token   — exchange PIN for a JWT access token
  POST /api/voice        — upload audio → STT → Trinity → TTS → audio response
  POST /api/ask          — send text   → Trinity → optional TTS → response
  GET  /api/status       — health check (unauthenticated)

Security
--------
  - JWT HS256 tokens with issuer/audience/jti claims (default TTL 8 h, max 24 h)
  - Local model and speech services stay on the Trinity host
  - Slowapi rate limiting plus an auth-failure lockout guard
  - CORS locked to configured origins in production

Environment variables required
-------------------------------
  TRINITY_APP_PIN_HASH   Salted PBKDF2 verifier generated by scripts/generate_app_pin_hash.py
  TRINITY_JWT_SECRET     Long random string used to sign JWTs
  LOCAL_LLM_URL          Local model runtime URL (default http://127.0.0.1:11434)
  TRINITY_*_MODEL        Optional local model overrides
  TRINITY_API_PORT       Port to listen on (default 8000)
  TRINITY_API_CORS       Comma-separated allowed origins; wildcard is loopback-only
  TRINITY_API_DEV_AUTH   Explicitly allow no-PIN/default-secret auth for loopback development only
  TRINITY_API_REMOTE_TRANSPORT  https or vpn for non-loopback exposure
  TRINITY_API_TLS_CERT / TRINITY_API_TLS_KEY  Required when remote transport is https

Run
---
  python -m core.run --mode daemon

The API is owned by the full Trinity runtime. Do not launch ``core.api`` as a
standalone second brain.
"""

from __future__ import annotations

import base64
import logging
import os
import sys
from datetime import datetime, timezone
from pathlib import Path
from typing import Optional

# Make sure Trinity's root is on the import path regardless of cwd
_ROOT = Path(__file__).resolve().parent.parent
if str(_ROOT) not in sys.path:
    sys.path.insert(0, str(_ROOT))

from fastapi import Depends, FastAPI, File, Form, HTTPException, Request, UploadFile
from fastapi.middleware.cors import CORSMiddleware
from fastapi.responses import JSONResponse
from fastapi.security import HTTPAuthorizationCredentials, HTTPBearer
from jose import JWTError, jwt
from pydantic import BaseModel
from slowapi import Limiter, _rate_limit_exceeded_handler
from slowapi.errors import RateLimitExceeded
from slowapi.util import get_remote_address

from core.api_bridge import ask_runtime, runtime_capabilities
from core.api_security import (
    DEFAULT_JWT_SECRET,
    DEFAULT_JWT_TTL_MINUTES,
    LoginAttemptGuard,
    bounded_jwt_ttl_minutes,
    build_jwt_claims,
    flag_enabled,
    strong_jwt_secret,
    verify_pin,
)
from core.trust_context import TrustContext, use_trust_context

logger = logging.getLogger(__name__)

# ── Configuration ─────────────────────────────────────────────────────────────

_APP_PIN_HASH    = os.environ.get("TRINITY_APP_PIN_HASH", "")
_JWT_SECRET      = os.environ.get("TRINITY_JWT_SECRET", DEFAULT_JWT_SECRET)
_JWT_ALGORITHM   = "HS256"
_JWT_ISSUER      = "trinity-local"
_JWT_AUDIENCE    = "trinity-mobile"
_JWT_TTL_MINUTES = bounded_jwt_ttl_minutes(
    os.environ.get("TRINITY_JWT_TTL_MINUTES", str(DEFAULT_JWT_TTL_MINUTES))
)
_CORS_ORIGINS    = [o.strip() for o in os.environ.get("TRINITY_API_CORS", "*").split(",") if o.strip()]

# ── FastAPI app ───────────────────────────────────────────────────────────────

limiter = Limiter(key_func=get_remote_address)

app = FastAPI(
    title="Trinity Voice API",
    version="1.0.0",
    docs_url=None,   # disable Swagger UI in production
    redoc_url=None,
)
app.state.limiter = limiter
app.add_exception_handler(RateLimitExceeded, _rate_limit_exceeded_handler)

app.add_middleware(
    CORSMiddleware,
    allow_origins=_CORS_ORIGINS,
    allow_methods=["GET", "POST"],
    allow_headers=["Authorization", "Content-Type"],
)

# ── Auth ──────────────────────────────────────────────────────────────────────

_security = HTTPBearer(auto_error=False)
_auth_guard = LoginAttemptGuard()


def _dev_auth_enabled() -> bool:
    return flag_enabled(os.environ.get("TRINITY_API_DEV_AUTH"))


def _verify_pin(pin: str) -> bool:
    return verify_pin(pin, _APP_PIN_HASH, dev_auth=_dev_auth_enabled())


def _create_token(sub: str = "david") -> str:
    if not strong_jwt_secret(_JWT_SECRET) and not _dev_auth_enabled():
        raise HTTPException(
            status_code=503,
            detail="TRINITY_JWT_SECRET must be configured before authenticated API use",
        )
    payload = build_jwt_claims(
        sub,
        ttl_minutes=_JWT_TTL_MINUTES,
        issuer=_JWT_ISSUER,
        audience=_JWT_AUDIENCE,
    )
    return jwt.encode(payload, _JWT_SECRET, algorithm=_JWT_ALGORITHM)


def _require_auth(
    creds: HTTPAuthorizationCredentials | None = Depends(_security),
) -> str:
    if creds is None:
        raise HTTPException(status_code=401, detail="Authentication required")
    try:
        payload = jwt.decode(
            creds.credentials,
            _JWT_SECRET,
            algorithms=[_JWT_ALGORITHM],
            audience=_JWT_AUDIENCE,
            issuer=_JWT_ISSUER,
        )
        sub: str = payload.get("sub", "")
        if not sub or not payload.get("jti"):
            raise HTTPException(status_code=401, detail="Invalid or expired token")
        return sub
    except JWTError as exc:
        raise HTTPException(status_code=401, detail="Invalid or expired token") from exc


# ── Pydantic models ───────────────────────────────────────────────────────────

class TokenRequest(BaseModel):
    pin: str


class AskRequest(BaseModel):
    text: str
    language: Optional[str] = None   # "english" | "tamil" — auto-detected if omitted
    tts: bool = True                  # include audio in response


class VoiceResponse(BaseModel):
    text_input: str
    text_response: str
    language: str
    audio_base64: Optional[str] = None   # locally rendered audio encoded as base64
    audio_format: Optional[str] = None


# ── Local speech services ─────────────────────────────────────────────────────

def _local_stt(audio_bytes: bytes, filename: str) -> str:
    """Transcribe an uploaded audio file using Trinity's local STT provider."""
    import tempfile
    from voice.local import LocalVoiceService

    suffix = Path(filename or "audio.wav").suffix or ".wav"
    path = None
    try:
        with tempfile.NamedTemporaryFile(suffix=suffix, delete=False) as tmp:
            tmp.write(audio_bytes)
            path = tmp.name
        result = LocalVoiceService().listen(path)
        if not result:
            raise RuntimeError(
                "Local speech recognition is unavailable. Install the configured Whisper provider."
            )
        return str(result.get("text", ""))
    finally:
        if path:
            Path(path).unlink(missing_ok=True)


def _tts(text: str, language: str) -> tuple[Optional[bytes], Optional[str]]:
    """Render speech locally when a byte-capable local TTS provider is available."""
    try:
        from voice.local import LocalVoiceService
        rendered = LocalVoiceService().render(text, language)
        if rendered is None:
            return None, None
        return rendered
    except Exception as exc:
        logger.warning("Local TTS unavailable: %s", exc)
        return None, None


# ── Language detection ────────────────────────────────────────────────────────

def _detect_language(text: str) -> str:
    try:
        from voice.language import LanguageDetector  # noqa: PLC0415
        return LanguageDetector().detect(text)
    except Exception:
        return "english"



# ── Trinity runtime binding ───────────────────────────────────────────────────

_brain = None


def _get_trinity():
    if _brain is None:
        raise HTTPException(
            status_code=503,
            detail="Trinity API is not bound to the full local runtime",
        )
    return _brain


def set_runtime_brain(runtime) -> None:
    """Bind API calls to the already-running full Trinity runtime."""
    global _brain  # noqa: PLW0603
    _brain = runtime


def _runtime_ask(text: str, trust_context: TrustContext | None = None) -> str:
    if trust_context is None:
        return ask_runtime(_get_trinity(), text)
    with use_trust_context(trust_context):
        return ask_runtime(_get_trinity(), text)


def _capabilities() -> dict:
    brain = _get_trinity()
    return runtime_capabilities(brain)



# ── Endpoints ─────────────────────────────────────────────────────────────────

@app.post("/api/auth/token")
@limiter.limit("5/minute")
async def get_token(request: Request, body: TokenRequest):
    """Exchange a PIN for a short-lived JWT access token."""
    client_id = request.client.host if request.client is not None else "unknown"
    guard = _auth_guard.check(client_id)
    if not guard.allowed:
        raise HTTPException(
            status_code=429,
            detail="Too many authentication failures",
            headers={"Retry-After": str(guard.retry_after_seconds)},
        )
    if not _verify_pin(body.pin):
        _auth_guard.record_failure(client_id)
        raise HTTPException(status_code=401, detail="Invalid credentials")
    _auth_guard.record_success(client_id)
    token = _create_token()
    return {
        "access_token": token,
        "token_type": "bearer",
        "expires_in": _JWT_TTL_MINUTES * 60,
    }


@app.post("/api/voice", response_model=VoiceResponse)
@limiter.limit("20/minute")
async def voice_endpoint(
    request:  Request,
    audio:    UploadFile = File(..., description="Recorded audio file (OGG/Opus preferred)"),
    language: Optional[str] = Form(None, description="'english' or 'tamil' — auto-detected if omitted"),
    tts:      bool = Form(True, description="Include TTS audio in response"),
    _user:    str  = Depends(_require_auth),
):
    """
    Full voice pipeline:
      Upload audio → local STT → Trinity brain → local TTS (when available) → response

    Audio formats supported: OGG/Opus (.ogg), WebM/Opus (.webm),
                             WAV/PCM (.wav), MP3 (.mp3)
    Preferred: OGG/Opus 16 kHz mono (smallest + highest quality)
    """
    # 1. Read and validate audio
    audio_bytes = await audio.read()
    if len(audio_bytes) > 10 * 1024 * 1024:
        raise HTTPException(status_code=400, detail="Audio too large (10 MB max)")
    if len(audio_bytes) < 100:
        raise HTTPException(status_code=400, detail="Audio too small — recording may be empty")

    # 2. Speech → Text
    try:
        transcript = _local_stt(audio_bytes, audio.filename or "audio.ogg")
    except Exception as exc:
        raise HTTPException(status_code=502, detail=f"Speech recognition error: {exc}") from exc

    if not transcript.strip():
        raise HTTPException(status_code=422, detail="No speech detected — please try again")

    # 3. Detect language if caller did not specify
    detected_lang = language or _detect_language(transcript)

    # 4. Ask Trinity
    try:
        response_text = _runtime_ask(
            transcript,
            TrustContext.verified_remote(subject=_user),
        )
    except Exception as exc:
        raise HTTPException(status_code=502, detail=f"Trinity brain error: {exc}") from exc

    # 5. Text → Speech
    audio_b64: Optional[str] = None
    audio_format: Optional[str] = None
    if tts:
        audio_bytes_out, audio_format = _tts(response_text, detected_lang)
        if audio_bytes_out:
            audio_b64 = base64.b64encode(audio_bytes_out).decode()

    return VoiceResponse(
        text_input=transcript,
        text_response=response_text,
        language=detected_lang,
        audio_base64=audio_b64,
        audio_format=audio_format,
    )


@app.post("/api/ask", response_model=VoiceResponse)
@limiter.limit("30/minute")
async def ask_endpoint(
    request: Request,
    body:    AskRequest,
    _user:   str = Depends(_require_auth),
):
    """
    Text-only pipeline — useful for testing, typing, or when STT is done on-device.

    Send text → Trinity brain → optional TTS audio response.
    """
    detected_lang = body.language or _detect_language(body.text)

    try:
        response_text = _runtime_ask(
            body.text,
            TrustContext.verified_remote(subject=_user),
        )
    except Exception as exc:
        raise HTTPException(status_code=502, detail=f"Trinity brain error: {exc}") from exc

    audio_b64: Optional[str] = None
    audio_format: Optional[str] = None
    if body.tts:
        audio_bytes_out, audio_format = _tts(response_text, detected_lang)
        if audio_bytes_out:
            audio_b64 = base64.b64encode(audio_bytes_out).decode()

    return VoiceResponse(
        text_input=body.text,
        text_response=response_text,
        language=detected_lang,
        audio_base64=audio_b64,
        audio_format=audio_format,
    )


@app.get("/api/status")
async def status():
    """Unauthenticated local health check."""
    return {
        "status": "ok" if _brain is not None else "starting",
        "version": "2.0-local",
        "time": datetime.now(timezone.utc).isoformat(),
        "runtime": "local",
        "runtime_bound": _brain is not None,
    }


@app.get("/api/capabilities")
async def capabilities(_user: str = Depends(_require_auth)):
    """Authenticated local runtime capability summary."""
    return _capabilities()


# ── Entry point ───────────────────────────────────────────────────────────────

if __name__ == "__main__":
    raise SystemExit(
        "The Trinity API must run inside the full local runtime. "
        "Start it with: python -m core.run --mode daemon"
    )
